let gamesdados = [
  {
    titulo: "Prince of Persia: The Lost Crown",
    descricao: "Prince of Persia: The Lost Crown é um jogo de ação e aventura que retorna às raízes da série com uma jogabilidade em 2D, focada em plataformas e combate ágil.",
    link: "https://pt.wikipedia.org/wiki/Prince_of_Persia:_The_Lost_Crown",
    imagem: "https://upload.wikimedia.org/wikipedia/en/a/a0/Prince_of_Persia_The_Lost_Crown_cover_art.jpg",
    plataforma: ["PC",  "PS5", "Xbox Series X/S"],
    genero: "Ação, Aventura",
    dataLancamento: "18 de janeiro de 2024",
    desenvolvedor: "Ubisoft",
    notaMedia: "8.5/10"
  },
  {
    titulo: "Black Myth: Wukong",
    descricao: "Black Myth: Wukong é um RPG de ação baseado na lenda chinesa do Rei Macaco, com gráficos impressionantes e uma jogabilidade desafiadora.",
    link: "https://pt.wikipedia.org/wiki/Black_Myth:_Wukong",
    imagem: "https://upload.wikimedia.org/wikipedia/en/a/a6/Black_Myth_Wukong_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "RPG, Ação",
    dataLancamento: "20 de agosto de 2024",
    desenvolvedor: "Game Science",
    notaMedia: "9.0/10"
  },
  {
    titulo: "Skull and Bones",
    descricao: "Skull and Bones é um jogo de ação e aventura focado em batalhas navais e pirataria, onde os jogadores podem explorar o oceano e combater outros piratas.",
    link: "https://pt.wikipedia.org/wiki/Skull_and_Bones",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/81/Skull_%26_Bones_video_game.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "Ação, Aventura",
    dataLancamento: "22 de agosto de 2024",
    desenvolvedor: "Ubisoft",
    notaMedia: "7.5/10"
  },
  {
    titulo: "Suicide Squad: Kill the Justice League",
    descricao: "Suicide Squad: Kill the Justice League é um jogo de ação e aventura onde os jogadores controlam membros do Esquadrão Suicida em uma missão para derrotar a Liga da Justiça.",
    link: "https://pt.wikipedia.org/wiki/Suicide_Squad:_Kill_the_Justice_League",
    imagem: "https://upload.wikimedia.org/wikipedia/en/2/2e/Suicide_Squad_Kill_the_Justice_League_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "Ação, Aventura",
    dataLancamento: "2 de fevereiro de 2024",
    desenvolvedor: "Rocksteady Studios",
    notaMedia: "8.0/10"
  },
  {
    titulo: "Dragon's Dogma 2",
    descricao: "Dragon's Dogma 2 é a sequência do popular RPG de ação, oferecendo um mundo aberto vasto e combates dinâmicos contra criaturas míticas.",
    link: "https://pt.wikipedia.org/wiki/Dragon's_Dogma_2",
    imagem: "https://upload.wikimedia.org/wikipedia/en/c/c7/Dragon%27s_Dogma_2_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "RPG, Ação",
    dataLancamento: "2024",
    desenvolvedor: "Capcom",
    notaMedia: "8.7/10"
  },
  {
    titulo: "Star Wars Outlaws",
    descricao: "Star Wars Outlaws é um jogo de ação e aventura ambientado no universo de Star Wars, onde os jogadores assumem o papel de um fora-da-lei em busca de fortuna.",
    link: "https://pt.wikipedia.org/wiki/Star_Wars_Outlaws",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/60/Star_Wars_Outlaws_2023.jpeg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "Ação, Aventura",
    dataLancamento: "2024",
    desenvolvedor: "Ubisoft",
    notaMedia: "8.3/10"
  },
  {
    titulo: "Tekken 8",
    descricao: "Tekken 8 é a mais recente entrada na famosa série de jogos de luta, trazendo novos personagens e mecânicas de combate aprimoradas.",
    link: "https://pt.wikipedia.org/wiki/Tekken_8",
    imagem: "https://upload.wikimedia.org/wikipedia/en/b/b4/Tekken_8_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "Luta",
    dataLancamento: "2024",
    desenvolvedor: "Bandai Namco",
    notaMedia: "8.9/10"
  },
  {
    titulo: "Persona 3 Reload",
    descricao: "Persona 3 Reload é um remake do clássico RPG Persona 3, com gráficos atualizados e melhorias na jogabilidade.",
    link: "https://pt.wikipedia.org/wiki/Persona_3_Reload",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/65/Persona_3_Reload_box_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "RPG",
    dataLancamento: "2024",
    desenvolvedor: "Atlus",
    notaMedia: "9.2/10"
  },
  {
    titulo: "Like A Dragon: Infinite Wealth",
    descricao: "Like A Dragon: Infinite Wealth é a mais recente entrada na série Yakuza, oferecendo uma narrativa envolvente e combates intensos.",
    link: "https://pt.wikipedia.org/wiki/Like_A_Dragon:_Infinite_Wealth",
    imagem: "https://upload.wikimedia.org/wikipedia/en/0/0f/Like_a_Dragon_Infinite_Wealth_Cover_Art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "Ação, Aventura",
    dataLancamento: "2024",
    desenvolvedor: "Ryu Ga Gotoku Studio",
    notaMedia: "8.8/10"
  },
  {
    titulo: "Final Fantasy VII Rebirth",
    descricao: "Final Fantasy VII Rebirth é a segunda parte do remake de Final Fantasy VII, continuando a história épica com gráficos deslumbrantes e jogabilidade aprimorada.",
    link: "https://pt.wikipedia.org/wiki/Final_Fantasy_VII_Rebirth",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/75/Boxart_for_Final_Fantasy_VII_Rebirth.png",
    plataforma: ["PC", "PS5"],
    genero: "RPG",
    dataLancamento: "2024",
    desenvolvedor: "Square Enix",
    notaMedia: "9.5/10"
  },
  {
    titulo: "Alone in the Dark",
    descricao: "Alone in the Dark é um jogo de terror e sobrevivência que reimagina o clássico original com gráficos modernos e uma atmosfera assustadora.",
    link: "https://pt.wikipedia.org/wiki/Alone_in_the_Dark",
    imagem: "https://upload.wikimedia.org/wikipedia/en/c/c2/Alone_in_the_Dark_1-2-3_logo.png",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "Terror, Sobrevivência",
    dataLancamento: "2024",
    desenvolvedor: "THQ Nordic",
    notaMedia: "7.8/10"
  },
  {
    titulo: "Princess Peach Showtime!",
    descricao: "Princess Peach Showtime! é um jogo de plataforma estrelado pela Princesa Peach, com uma jogabilidade divertida e colorida.",
    link: "https://pt.wikipedia.org/wiki/Princess_Peach_Showtime!",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/86/Peachshowtime.png",
    plataforma: ["Nintendo Switch"],
    genero: "Plataforma",
    dataLancamento: "2024",
    desenvolvedor: "Nintendo",
    notaMedia: "8.0/10"
  },
  {
    titulo: "Rise of the Ronin",
    descricao: "Rise of the Ronin é um RPG de ação ambientado no Japão feudal, onde os jogadores assumem o papel de um ronin em busca de vingança.",
    link: "https://pt.wikipedia.org/wiki/Rise_of_the_Ronin",
    imagem: "https://upload.wikimedia.org/wikipedia/en/b/bf/Rise_of_the_Ronin_Key_Art.jpg",
    plataforma: ["PC", "PS5"],
    genero: "RPG, Ação",
    dataLancamento: "2024",
    desenvolvedor: "Team Ninja",
    notaMedia: "8.6/10"
  },
  {
    titulo: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
    descricao: "S.T.A.L.K.E.R. 2: Heart of Chornobyl é um jogo de tiro em primeira pessoa com elementos de sobrevivência, ambientado na zona de exclusão de Chernobyl.",
    link: "https://pt.wikipedia.org/wiki/S.T.A.L.K.E.R._2:_Heart_of_Chornobyl",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/80/STALKER_2_cover_art.jpg",
    plataforma: ["PC", "Xbox Series X/S"],
    genero: "Tiro, Sobrevivência",
    dataLancamento: "8 de dezembro de 2024",
    desenvolvedor: "GSC Game World",
    notaMedia: "8.4/10"
  },
  {
    titulo: "Vampire: The Masquerade - Bloodlines 2",
    descricao: "Vampire: The Masquerade - Bloodlines 2 é um RPG de ação ambientado em um mundo de vampiros, onde os jogadores devem navegar pela política e perigos da sociedade vampírica.",
    link: "https://pt.wikipedia.org/wiki/Vampire:_The_Masquerade_–_Bloodlines_2",
    imagem: "https://upload.wikimedia.org/wikipedia/en/d/de/Vampire_The_Masquerade_%E2%80%93_Bloodlines_2_%282024%29_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X/S"],
    genero: "RPG, Ação",
    dataLancamento: "2024",
    desenvolvedor: "Hardsuit Labs",
    notaMedia: "8.1/10"
  },
  {
    titulo: "Paper Mario: The Thousand-Year Door",
    descricao: "Paper Mario: The Thousand-Year Door é um RPG de ação e aventura com uma estética única de papel, onde Mario deve salvar o mundo de uma ameaça antiga.",
    link: "https://pt.wikipedia.org/wiki/Paper_Mario:_The_Thousand-Year_Door",
    imagem: "https://upload.wikimedia.org/wikipedia/en/1/18/Paper_Mario_The_Thousand-Year_Door_%28artwork%29.jpg",
    plataforma: ["Nintendo Switch"],
    genero: "RPG, Aventura",
    dataLancamento: "2024",
    desenvolvedor: "Intelligent Systems",
    notaMedia: "9.0/10"
  },
  {
    titulo: "Senua's Saga: Hellblade II",
    descricao: "Senua's Saga: Hellblade II é a sequência do aclamado Hellblade: Senua's Sacrifice, continuando a jornada de Senua enquanto ela enfrenta novos desafios e inimigos em um mundo sombrio e místico.",
    link: "https://pt.wikipedia.org/wiki/Senuas_Saga:_Hellblade_II",
    imagem: "https://upload.wikimedia.org/wikipedia/en/e/ed/Senua%27s_Saga_Hellblade_II_cover_art.png",
    plataforma: ["PC", "Xbox Series X/S"],
    genero: "Ação, Aventura",
    dataLancamento: "2024",
    desenvolvedor: "Ninja Theory",
    notaMedia: "9.3/10"
  },
  {
    titulo: "Devil May Cry: Peak of Combat",
    descricao: "Um jogo de ação e aventura da série Devil May Cry.",
    link: "https://en.wikipedia.org/wiki/Devil_May_Cry:_Peak_of_Combat",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Devil_May_Cry_Peak_of_Combat.jpg",
    plataforma: ["iOS", "Android"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-11",
    desenvolvedor: "Yunchang Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Momodora: Moonlit Farewell",
    descricao: "Um jogo de plataforma e ação com elementos de metroidvania.",
    link: "https://en.wikipedia.org/wiki/Momodora:_Moonlit_Farewell",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Momodora_Moonlit_Farewell.jpg",
    plataforma: ["PC"],
    genero: "Plataforma, Ação",
    dataLancamento: "2024-01-11",
    desenvolvedor: "Bombservice",
    notamedia: "Não definido"
  },
  {
    titulo: "Unstoppable",
    descricao: "Um jogo de ação e aventura.",
    link: "https://en.wikipedia.org/wiki/Unstoppable_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Unstoppable_video_game.jpg",
    plataforma: ["PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-11",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Radiance",
    descricao: "Um jogo de ação e aventura.",
    link: "https://en.wikipedia.org/wiki/Radiance_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/2/2e/Radiance_video_game.jpg",
    plataforma: ["PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-11",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Ravendawn",
    descricao: "Um MMORPG com um mundo aberto e dinâmico.",
    link: "https://en.wikipedia.org/wiki/Ravendawn",
    imagem: "https://upload.wikimedia.org/wikipedia/en/1/1e/Ravendawn.jpg",
    plataforma: ["PC"],
    genero: "MMORPG",
    dataLancamento: "2024-01-16",
    desenvolvedor: "Living Phoenix Entertainment",
    notamedia: "Não definido"
  },
  {
    titulo: "The Temple Of",
    descricao: "Um jogo de aventura e quebra-cabeça.",
    link: "https://en.wikipedia.org/wiki/The_Temple_Of",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/The_Temple_Of.jpg",
    plataforma: ["PC"],
    genero: "Aventura, Quebra-cabeça",
    dataLancamento: "2024-01-16",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Atlas Wept",
    descricao: "Um jogo de estratégia e aventura.",
    link: "https://en.wikipedia.org/wiki/Atlas_Wept",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Atlas_Wept.jpg",
    plataforma: ["PC"],
    genero: "Estratégia, Aventura",
    dataLancamento: "2024-01-17",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Immortal Life",
    descricao: "Um jogo de simulação de vida com elementos de RPG.",
    link: "https://en.wikipedia.org/wiki/Immortal_Life",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Immortal_Life.jpg",
    plataforma: ["PC"],
    genero: "Simulação, RPG",
    dataLancamento: "2024-01-18",
    desenvolvedor: "YiFang Studio",
    notamedia: "Não definido"
  },
  {
    titulo: "Prince of Persia: The Lost Crown",
    descricao: "Um jogo de ação e aventura da série Prince of Persia.",
    link: "https://en.wikipedia.org/wiki/Prince_of_Persia:_The_Lost_Crown",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Prince_of_Persia_The_Lost_Crown.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-18",
    desenvolvedor: "Ubisoft",
    notamedia: "Não definido"
  },
  {
    titulo: "Arclands",
    descricao: "Um jogo de estratégia e construção de cidades.",
    link: "https://en.wikipedia.org/wiki/Arclands",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Arclands.jpg",
    plataforma: ["PC"],
    genero: "Estratégia, Construção",
    dataLancamento: "2024-01-19",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Another Code: Recollection",
    descricao: "Um jogo de aventura e mistério.",
    link: "https://en.wikipedia.org/wiki/Another_Code:_Recollection",
    imagem: "https://upload.wikimedia.org/wikipedia/en/0/0e/Another_Code_Recollection.jpg",
    plataforma: ["Switch"],
    genero: "Aventura, Mistério",
    dataLancamento: "2024-01-19",
    desenvolvedor: "Cing",
    notamedia: "Não definido"
  },
  {
    titulo: "The Last of Us Part 2: Remastered",
    descricao: "Uma versão remasterizada do aclamado jogo de ação e aventura.",
    link: "https://en.wikipedia.org/wiki/The_Last_of_Us_Part_2:_Remastered",
    imagem: "https://upload.wikimedia.org/wikipedia/en/1/1e/The_Last_of_Us_Part_2_Remastered.jpg",
    plataforma: ["PS5"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-19",
    desenvolvedor: "Naughty Dog",
    notamedia: "Não definido"
  },
  {
    titulo: "Graven",
    descricao: "Um jogo de ação e aventura com elementos de RPG.",
    link: "https://en.wikipedia.org/wiki/Graven",
    imagem: "https://upload.wikimedia.org/wikipedia/en/2/2e/Graven.jpg",
    plataforma: ["PC"],
    genero: "Ação, Aventura, RPG",
    dataLancamento: "2024-01-23",
    desenvolvedor: "Slipgate Ironworks",
    notamedia: "Não definido"
  },
  {
    titulo: "Howl",
    descricao: "Um jogo de ação e aventura.",
    link: "https://en.wikipedia.org/wiki/Howl_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Howl_video_game.jpg",
    plataforma: ["PS5", "Xbox Series X|S"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-23",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Soundscape",
    descricao: "Um jogo de música e ritmo.",
    link: "https://en.wikipedia.org/wiki/Soundscape_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Soundscape_video_game.jpg",
    plataforma: ["PC"],
    genero: "Música, Ritmo",
    dataLancamento: "2024-01-23",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "AdventureQuest 8-Bit: Dungeons & DoomKnights",
    descricao: "Um jogo de RPG e aventura com gráficos retrô.",
    link: "https://en.wikipedia.org/wiki/AdventureQuest_8-Bit:_Dungeons_%26_DoomKnights",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/AdventureQuest_8-Bit_Dungeons_%26_DoomKnights.jpg",
    plataforma: ["PC", "Switch"],
    genero: "RPG, Aventura",
    dataLancamento: "2024-01-25",
    desenvolvedor: "Artix Entertainment",
    notamedia: "Não definido"
  },
  {
    titulo: "Apollo Justice Ace Attorney Trilogy",
    descricao: "Uma coleção de três jogos da série Ace Attorney, focada no personagem Apollo Justice.",
    link: "https://en.wikipedia.org/wiki/Apollo_Justice:_Ace_Attorney_Trilogy",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Apollo_Justice_Ace_Attorney_Trilogy.jpg",
    plataforma: ["Switch"],
    genero: "Aventura, Visual Novel",
    dataLancamento: "2024-01-25",
    desenvolvedor: "Capcom",
    notamedia: "Não definido"
  },
  {
    titulo: "Go Mecha Ball",
    descricao: "Um jogo de ação e aventura com mechas.",
    link: "https://en.wikipedia.org/wiki/Go_Mecha_Ball",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Go_Mecha_Ball.jpg",
    plataforma: ["Xbox Series X|S", "Xbox One", "PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-01-25",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Phantom Abyss",
    descricao: "Um jogo de exploração em primeira pessoa com elementos de roguelike.",
    link: "https://en.wikipedia.org/wiki/Phantom_Abyss",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Phantom_Abyss.jpg",
    plataforma: ["PC", "Xbox Series X|S"],
    genero: "Exploração, Roguelike",
    dataLancamento: "2024-01-25",
    desenvolvedor: "Team WIBY",
    notamedia: "Não definido"
  },
  {
    titulo: "RIN: The Last Child",
    descricao: "Um jogo de ação e aventura com elementos de RPG.",
    link: "https://en.wikipedia.org/wiki/RIN:_The_Last_Child",
    imagem: "https://upload.wikimedia.org/wikipedia/en/2/2e/RIN_The_Last_Child.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "Switch", "PC"],
    genero: "Ação, Aventura, RPG",
    dataLancamento: "2024-01-25",
    desenvolvedor: "Space Fox Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Under Night In-Birth II Sys:Celes",
    descricao: "Um jogo de luta com personagens únicos e uma história envolvente.",
    link: "https://en.wikipedia.org/wiki/Under_Night_In-Birth_II_Sys:Celes",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Under_Night_In-Birth_II_Sys_Celes.jpg",
    plataforma: ["PS5", "PS4", "Switch", "PC"],
    genero: "Luta",
    dataLancamento: "2024-01-25",
    desenvolvedor: "French Bread",
    notamedia: "Não definido"
  },
  {
    titulo: "Like a Dragon: Infinite Wealth",
    descricao: "Um jogo de RPG e ação da série Yakuza.",
    link: "https://en.wikipedia.org/wiki/Like_a_Dragon:_Infinite_Wealth",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Like_a_Dragon_Infinite_Wealth.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
    genero: "RPG, Ação",
    dataLancamento: "2024-01-26",
    desenvolvedor: "Ryu Ga Gotoku Studio",
    notamedia: "Não definido"
  },
  {
    titulo: "Tekken 8",
    descricao: "O oitavo jogo principal da série de luta Tekken.",
    link: "https://en.wikipedia.org/wiki/Tekken_8",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Tekken_8.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "Luta",
    dataLancamento: "2024-01-26",
    desenvolvedor: "Bandai Namco Entertainment",
    notamedia: "Não definido"
  },
  {
    titulo: "Chronique des Silencieux",
    descricao: "Um jogo de aventura e mistério.",
    link: "https://en.wikipedia.org/wiki/Chronique_des_Silencieux",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Chronique_des_Silencieux.jpg",
    plataforma: ["PC"],
    genero: "Aventura, Mistério",
    dataLancamento: "2024-01-29",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Rugby 24",
    descricao: "Um jogo de simulação de rugby.",
    link: "https://en.wikipedia.org/wiki/Rugby_24",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Rugby_24.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
    genero: "Esporte, Simulação",
    dataLancamento: "2024-01-30",
    desenvolvedor: "Nacon",
    notamedia: "Não definido"
  },
  {
    titulo: "Silent Hill: The Short Message",
    descricao: "Um jogo de terror e sobrevivência da série Silent Hill.",
    link: "https://en.wikipedia.org/wiki/Silent_Hill:_The_Short_Message",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Silent_Hill_The_Short_Message.jpg",
    plataforma: ["PS5"],
    genero: "Terror, Sobrevivência",
    dataLancamento: "2024-01-31",
    desenvolvedor: "Konami",
    notamedia: "Não definido"
  },
  {
    titulo: "Boxes: Lost Fragments",
    descricao: "Um jogo de quebra-cabeça e aventura.",
    link: "https://en.wikipedia.org/wiki/Boxes:_Lost_Fragments",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Boxes_Lost_Fragments.jpg",
    plataforma: ["PC"],
    genero: "Quebra-cabeça, Aventura",
    dataLancamento: "2024-02-01",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Granblue Fantasy: Relink",
    descricao: "Um RPG de ação baseado no popular jogo mobile Granblue Fantasy.",
    link: "https://en.wikipedia.org/wiki/Granblue_Fantasy:_Relink",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Granblue_Fantasy_Relink.jpg",
    plataforma: ["PS5", "PS4", "PC"],
    genero: "RPG, Ação",
    dataLancamento: "2024-02-01",
    desenvolvedor: "Cygames",
    notamedia: "Não definido"
  },
  {
    titulo: "Project Demigod",
    descricao: "Um jogo de ação e aventura em realidade virtual.",
    link: "https://en.wikipedia.org/wiki/Project_Demigod",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Project_Demigod.jpg",
    plataforma: ["Quest 2", "Quest 3", "Quest Pro", "PC VR"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-02-01",
    desenvolvedor: "Desenvolvedor Desconhecido",
    notamedia: "Não definido"
  },
  {
    titulo: "Jujutsu Kaisen Cursed Clash",
    descricao: "Um jogo de luta baseado no popular anime Jujutsu Kaisen.",
    link: "https://en.wikipedia.org/wiki/Jujutsu_Kaisen_Cursed_Clash",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Jujutsu_Kaisen_Cursed_Clash.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "Switch", "PC"],
    genero: "Luta",
    dataLancamento: "2024-02-02",
    desenvolvedor: "Bandai Namco Entertainment",
    notamedia: "Não definido"
  },
  {
    titulo: "Suicide Squad: Kill the Justice League",
    descricao: "Um jogo de ação e aventura onde os membros do Esquadrão Suicida devem enfrentar a Liga da Justiça.",
    link: "https://en.wikipedia.org/wiki/Suicide_Squad:_Kill_the_Justice_League",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8b/Suicide_Squad_Kill_the_Justice_League.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-02-02",
    desenvolvedor: "Rocksteady Studios",
    notamedia: "Não definido"
  },
  {
    titulo: "Persona 3 Reload",
    descricao: "Uma versão remasterizada do clássico RPG Persona 3.",
    link: "https://en.wikipedia.org/wiki/Persona_3_Reload",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Persona_3_Reload.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
    genero: "RPG",
    dataLancamento: "2024-02-02",
    desenvolvedor: "Atlus",
    notamedia: "Não definido"
  },
  {
    titulo: "Clem",
    descricao: "Um jogo de aventura e quebra-cabeça com uma narrativa envolvente.",
    link: "https://en.wikipedia.org/wiki/Clem",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Clem.jpg",
    plataforma: ["PC", "Switch"],
    genero: "Aventura, Quebra-cabeça",
    dataLancamento: "2024-02-06",
    desenvolvedor: "Mango Protocol",
    notamedia: "Não definido"
  },
  {
    titulo: "Touhou Danmaku Kagura Phantasia Lost",
    descricao: "Um jogo de ação rítmica baseado no universo de Touhou Project.",
    link: "https://en.wikipedia.org/wiki/Touhou_Danmaku_Kagura_Phantasia_Lost",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Touhou_Danmaku_Kagura_Phantasia_Lost.jpg",
    plataforma: ["PC"],
    genero: "Ação, Rítmico",
    dataLancamento: "2024-02-07",
    desenvolvedor: "Unknown X",
    notamedia: "Não definido"
  },
  {
    titulo: "Helldivers 2",
    descricao: "Um jogo de tiro em terceira pessoa com foco em cooperação e combate intenso.",
    link: "https://en.wikipedia.org/wiki/Helldivers_2",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Helldivers_2.jpg",
    plataforma: ["PS5", "PC"],
    genero: "Tiro, Ação",
    dataLancamento: "2024-02-08",
    desenvolvedor: "Arrowhead Game Studios",
    notamedia: "Não definido"
  },
  {
    titulo: "Konosuba - God's Blessing On This Wonderful World! Love For These Clothes Of Desire",
    descricao: "Visual novel baseada na série Konosuba, onde Kazuma e seus amigos enfrentam uma maldição que altera suas personalidades.",
    link: "https://en.wikipedia.org/wiki/Konosuba:_God%27s_Blessing_on_This_Wonderful_World!_Love_For_These_Clothes_Of_Desire!",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Konosuba_Love_For_These_Clothes_Of_Desire.jpg",
    plataforma: ["PC", "PS4", "Switch"],
    genero: "Visual Novel",
    dataLancamento: "2024-02-08",
    desenvolvedor: "MAGES. Inc.",
    notamedia: "Não definido"
  },
  {
    titulo: "Banishers: Ghosts of New Eden",
    descricao: "RPG de ação onde você caça fantasmas em um mundo sombrio e cheio de mistérios.",
    link: "https://en.wikipedia.org/wiki/Banishers:_Ghosts_of_New_Eden",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Banishers_Ghosts_of_New_Eden.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "RPG de Ação",
    dataLancamento: "2024-02-13",
    desenvolvedor: "Don't Nod",
    notamedia: "Não definido"
  },
  {
    titulo: "Lysfanga: The Time Shift Warrior",
    descricao: "Jogo de ação tática onde você manipula o tempo para criar clones de si mesmo e lutar contra hordas de inimigos.",
    link: "https://en.wikipedia.org/wiki/Lysfanga:_The_Time_Shift_Warrior",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Lysfanga_The_Time_Shift_Warrior.jpg",
    plataforma: ["PC"],
    genero: "Ação Tática",
    dataLancamento: "2024-02-13",
    desenvolvedor: "Sand Door Studio",
    notamedia: "Não definido"
  },
  {
    titulo: "Ultros",
    descricao: "Aventura psicodélica de ficção científica onde você explora um útero cósmico e enfrenta seres demoníacos.",
    link: "https://en.wikipedia.org/wiki/Ultros",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Ultros.jpg",
    plataforma: ["PS5", "PS4", "PC"],
    genero: "Aventura",
    dataLancamento: "2024-02-13",
    desenvolvedor: "Hadoque",
    notamedia: "Não definido"
  },
  {
    titulo: "Solim Infernum",
    descricao: "Jogo de estratégia onde você compete pelo trono do inferno, utilizando táticas políticas e militares.",
    link: "https://en.wikipedia.org/wiki/Solium_Infernum",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Solium_Infernum.jpg",
    plataforma: ["PC"],
    genero: "Estratégia",
    dataLancamento: "2024-02-14",
    desenvolvedor: "League of Geeks",
    notamedia: "Não definido"
  },
  {
    titulo: "Sucker for Love: Date to Die For",
    descricao: "Jogo de terror e romance onde você deve conquistar o coração de entidades lovecraftianas.",
    link: "https://en.wikipedia.org/wiki/Sucker_for_Love:_Date_to_Die_For",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Sucker_for_Love_Date_to_Die_For.jpg",
    plataforma: ["PC"],
    genero: "Terror, Romance",
    dataLancamento: "2024-02-14",
    desenvolvedor: "Akabaka",
    notamedia: "Não definido"
  },
  {
    titulo: "Titanic: A Space Between",
    descricao: "Experiência de realidade virtual que recria o naufrágio do Titanic.",
    link: "https://en.wikipedia.org/wiki/Titanic:_A_Space_Between",
    imagem: "https://upload.wikimedia.org/wikipedia/en/2/2e/Titanic_A_Space_Between.jpg",
    plataforma: ["Quest"],
    genero: "Realidade Virtual, História",
    dataLancamento: "2024-02-14",
    desenvolvedor: "Immersive VR Education",
    notamedia: "Não definido"
  },
  {
    titulo: "Tomb Raider 1-3 Remastered",
    descricao: "Remasterização dos três primeiros jogos da série Tomb Raider.",
    link: "https://en.wikipedia.org/wiki/Tomb_Raider_1-3_Remastered",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Tomb_Raider_1-3_Remastered.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "Switch", "PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-02-14",
    desenvolvedor: "Crystal Dynamics",
    notamedia: "Não definido"
  },
  {
    titulo: "Clash II",
    descricao: "Jogo de estratégia em tempo real com batalhas épicas e construção de impérios.",
    link: "https://en.wikipedia.org/wiki/Clash_II",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Clash_II.jpg",
    plataforma: ["PC"],
    genero: "Estratégia em Tempo Real",
    dataLancamento: "2024-02-15",
    desenvolvedor: "Prime Bit Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Gunvolt Records Cychronicle",
    descricao: "Jogo de ação e plataforma com elementos de RPG.",
    link: "https://en.wikipedia.org/wiki/Gunvolt_Records_Cychronicle",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Gunvolt_Records_Cychronicle.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "Switch", "PC"],
    genero: "Ação, Plataforma",
    dataLancamento: "2024-02-15",
    desenvolvedor: "Inti Creates",
    notamedia: "Não definido"
  },
  {
    titulo: "PlateUp!",
    descricao: "Jogo de simulação de restaurante onde você gerencia e cozinha pratos para os clientes.",
    link: "https://en.wikipedia.org/wiki/PlateUp!",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/PlateUp!.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Switch"],
    genero: "Simulação",
    dataLancamento: "2024-02-15",
    desenvolvedor: "It's Happening",
    notamedia: "Não definido"
  },
  {
    titulo: "RC Revolution",
    descricao: "Jogo de corrida com carros de controle remoto.",
    link: "https://en.wikipedia.org/wiki/RC_Revolution",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/RC_Revolution.jpg",
    plataforma: ["PC"],
    genero: "Corrida",
    dataLancamento: "2024-02-15",
    desenvolvedor: "Tiny Digital Factory",
    notamedia: "Não definido"
  },
  {
    titulo: "Survivorman VR: The Descent",
    descricao: "Jogo de sobrevivência em realidade virtual baseado na série de TV Survivorman.",
    link: "https://en.wikipedia.org/wiki/Survivorman_VR:_The_Descent",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Survivorman_VR_The_Descent.jpg",
    plataforma: ["PSVR 2", "PC VR"],
    genero: "Sobrevivência, Realidade Virtual",
    dataLancamento: "2024-02-15",
    desenvolvedor: "Cream Productions",
    notamedia: "Não definido"
  },
  {
    titulo: "Mario vs. Donkey Kong",
    descricao: "Jogo de quebra-cabeça e plataforma onde Mario enfrenta Donkey Kong para resgatar Pauline.",
    link: "https://en.wikipedia.org/wiki/Mario_vs._Donkey_Kong",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Mario_vs._Donkey_Kong.jpg",
    plataforma: ["Switch"],
    genero: "Quebra-cabeça, Plataforma",
    dataLancamento: "2024-02-16",
    desenvolvedor: "Nintendo",
    notamedia: "Não definido"
  },
  {
    titulo: "Skull and Bones",
    descricao: "Jogo de ação naval onde você comanda um navio pirata e participa de batalhas épicas no mar.",
    link: "https://en.wikipedia.org/wiki/Skull_and_Bones_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Skull_and_Bones_cover_art.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "Ação, Aventura",
    dataLancamento: "2024-02-16",
    desenvolvedor: "Ubisoft",
    notamedia: "Não definido"
  },
  {
    titulo: "Furnish Master",
    descricao: "Jogo de simulação onde você decora apartamentos, casas e propriedades comerciais.",
    link: "https://en.wikipedia.org/wiki/Furnish_Master",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Furnish_Master.jpg",
    plataforma: ["PC"],
    genero: "Simulação",
    dataLancamento: "2024-02-20",
    desenvolvedor: "Alex Blintsov",
    notamedia: "Não definido"
  },
  {
    titulo: "Nightingale",
    descricao: "Jogo de sobrevivência em mundo aberto onde você explora reinos misteriosos e enfrenta criaturas perigosas.",
    link: "https://en.wikipedia.org/wiki/Nightingale_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Nightingale_cover_art.jpg",
    plataforma: ["PC"],
    genero: "Sobrevivência, Aventura",
    dataLancamento: "2024-02-20",
    desenvolvedor: "Inflexion Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Qomp2",
    descricao: "Jogo de plataforma e quebra-cabeça que reimagina o clássico Pong.",
    link: "https://en.wikipedia.org/wiki/Qomp2",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Qomp2_cover_art.jpg",
    plataforma: ["Xbox Series X|S", "Xbox One", "PS5", "PS4", "Switch", "PC"],
    genero: "Plataforma, Quebra-cabeça",
    dataLancamento: "2024-02-20",
    desenvolvedor: "Atari",
    notamedia: "Não definido"
  },
  {
    titulo: "The Lost Legends of Redwall: Feast & Friends",
    descricao: "Jogo de simulação de culinária baseado na série de livros Redwall.",
    link: "https://en.wikipedia.org/wiki/The_Lost_Legends_of_Redwall:_Feast_%26_Friends",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/The_Lost_Legends_of_Redwall_Feast_%26_Friends_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X|S"],
    genero: "Simulação, Culinária",
    dataLancamento: "2024-02-20",
    desenvolvedor: "Soma Games",
    notamedia: "Não definido"
  },
  {
    titulo: "The Lost Legends of Redwall: The Scout Anthology",
    descricao: "Jogo de aventura baseado na série de livros Redwall.",
    link: "https://en.wikipedia.org/wiki/The_Lost_Legends_of_Redwall:_The_Scout_Anthology",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/The_Lost_Legends_of_Redwall_The_Scout_Anthology_cover_art.jpg",
    plataforma: ["PC", "PS5", "Xbox Series X|S"],
    genero: "Aventura",
    dataLancamento: "2024-02-20",
    desenvolvedor: "Soma Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Warhammer 40,000: Chaos Gate - Daemonhunters",
    descricao: "Jogo de estratégia baseado no universo Warhammer 40,000.",
    link: "https://en.wikipedia.org/wiki/Warhammer_40,000:_Chaos_Gate_-_Daemonhunters",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Warhammer_40,000_Chaos_Gate_-_Daemonhunters_cover_art.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One"],
    genero: "Estratégia",
    dataLancamento: "2024-02-20",
    desenvolvedor: "Complex Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Bandle Tale: A League of Legends Story",
    descricao: "Jogo de aventura ambientado no universo de League of Legends.",
    link: "https://en.wikipedia.org/wiki/Bandle_Tale:_A_League_of_Legends_Story",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Bandle_Tale_A_League_of_Legends_Story_cover_art.jpg",
    plataforma: ["Switch", "PC"],
    genero: "Aventura",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Riot Forge",
    notamedia: "Não definido"
  },
  {
    titulo: "Last Epoch",
    descricao: "Jogo de RPG de ação com elementos de hack and slash.",
    link: "https://en.wikipedia.org/wiki/Last_Epoch",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Last_Epoch_cover_art.jpg",
    plataforma: ["PC"],
    genero: "RPG de Ação",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Eleventh Hour Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Myth of Empires",
    descricao: "Jogo de sobrevivência e construção em um mundo de fantasia.",
    link: "https://en.wikipedia.org/wiki/Myth_of_Empires",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Myth_of_Empires_cover_art.jpg",
    plataforma: ["PC"],
    genero: "Sobrevivência, Construção",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Angela Game",
    notamedia: "Não definido"
  },
  {
    titulo: "Penny's Big Breakaway",
    descricao: "Jogo de plataforma onde você controla Penny em uma aventura cheia de desafios.",
    link: "https://en.wikipedia.org/wiki/Penny%27s_Big_Breakaway",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Penny%27s_Big_Breakaway_cover_art.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "Switch", "PC"],
    genero: "Plataforma",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Evening Star",
    notamedia: "Não definido"
  },
  {
    titulo: "Pocket Card Jockey: Ride On",
    descricao: "Jogo de corrida de cavalos com elementos de cartas.",
    link: "https://en.wikipedia.org/wiki/Pocket_Card_Jockey:_Ride_On",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Pocket_Card_Jockey_Ride_On_cover_art.jpg",
    plataforma: ["Switch"],
    genero: "Corrida, Cartas",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Game Freak",
    notamedia: "Não definido"
  },
  {
    titulo: "Slave Zero X",
    descricao: "Jogo de ação e plataforma com temática cyberpunk.",
    link: "https://en.wikipedia.org/wiki/Slave_Zero_X",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Slave_Zero_X_cover_art.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "Switch", "PC"],
    genero: "Ação, Plataforma",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Ziggurat Interactive",
    notamedia: "Não definido"
  },
  {
    titulo: "Terminator Dark Fate - Defiance",
    descricao: "Jogo de estratégia baseado no universo de Terminator.",
    link: "https://en.wikipedia.org/wiki/Terminator_Dark_Fate_-_Defiance",
    imagem: "https://upload.wikimedia.org/wikipedia/en/9/9e/Terminator_Dark_Fate_-_Defiance_cover_art.jpg",
    plataforma: ["PC"],
    genero: "Estratégia",
    dataLancamento: "2024-02-21",
    desenvolvedor: "Cats Who Play",
    notamedia: "Não definido"
  },
  {
    titulo: "CorpoNation: The Sorting Process",
    descricao: "Um jogo de simulação de gestão corporativa onde você organiza amostras genéticas.",
    link: "https://en.wikipedia.org/wiki/CorpoNation:_The_Sorting_Process",
    imagem: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/CorpoNation_The_Sorting_Process.jpg/220px-CorpoNation_The_Sorting_Process.jpg",
    plataforma: ["PC"],
    genero: "Simulação",
    dataLancamento: "2024-02-22",
    desenvolvedor: "Canteen",
    notamedia: "Não definido"
  },
  {
    titulo: "Garden Life: A Cozy Life Simulator",
    descricao: "Um simulador de jardinagem relaxante onde você cria o jardim dos seus sonhos.",
    link: "https://en.wikipedia.org/wiki/Garden_Life:_A_Cozy_Life_Simulator",
    imagem: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Garden_Life_A_Cozy_Life_Simulator.jpg/220px-Garden_Life_A_Cozy_Life_Simulator.jpg",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "PC"],
    genero: "Simulação",
    dataLancamento: "2024-02-22",
    desenvolvedor: "Stillalive Studios",
    notamedia: "Não definido"
  },
  {
    titulo: "Inkulinati",
    descricao: "Um jogo de estratégia baseado em tinta saído de manuscritos medievais.",
    link: "https://en.wikipedia.org/wiki/Inkulinati",
    imagem: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/Inkulinati.jpg/220px-Inkulinati.jpg",
    plataforma: ["Xbox Series X|S", "Xbox One", "Switch", "PC"],
    genero: "Estratégia",
    dataLancamento: "2024-02-22",
    desenvolvedor: "Yaza Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Nyaaaanvy",
    descricao: "Um jogo de luta de sumô baseado em física com criaturas misteriosas parecidas com gatos.",
    link: "https://en.wikipedia.org/wiki/Nyaaaanvy",
    imagem: "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Nyaaaanvy.jpg/220px-Nyaaaanvy.jpg",
    plataforma: ["Switch", "PC"],
    genero: "Ação",
    dataLancamento: "2024-02-22",
    desenvolvedor: "Team DigitalMind",
    notamedia: "Não definido"
  },
  {
    titulo: "Pacific Drive",
    descricao: "Um jogo de sobrevivência de direção ambientado na Península Olímpica.",
    link: "https://en.wikipedia.org/wiki/Pacific_Drive",
    imagem: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Pacific_Drive.jpg/220px-Pacific_Drive.jpg",
    plataforma: ["PS5", "PC"],
    genero: "Sobrevivência",
    dataLancamento: "2024-02-22",
    desenvolvedor: "Ironwood Studios",
    notamedia: "Não definido"
  },
  {
    titulo: "Rail Route",
    descricao: "Em Rail Route, você projetará, construirá, atualizará e automatizará sua rede ferroviária em um dos muitos mapas baseados em cidades reais ao redor do mundo.",
    link: "https://en.wikipedia.org/wiki/Rail_Route",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Rail_Route_cover_art.jpg",
    plataforma: "PC",
    genero: "Simulação",
    dataLancamento: "2024-02-22",
    desenvolvedor: "Bitrich.info",
    notamedia: "Não definido"
  },
  {
    titulo: "Feud",
    descricao: "Feud é um jogo de estratégia por turnos. Troque peças em uma grade de quatro por quatro para isolar as peças do seu oponente ou vá direto para o Rei.",
    link: "https://en.wikipedia.org/wiki/Feud_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Feud_cover_art.jpg",
    plataforma: "PC, iOS, Android",
    genero: "Estratégia",
    dataLancamento: "2024-02-23",
    desenvolvedor: "Bearwaves",
    notamedia: "Não definido"
  },
  {
    titulo: "Dicefolk",
    descricao: "Dicefolk é um roguelike de construção de baralhos onde você deve recrutar quimeras, personalizar seus dados e desbloquear artefatos poderosos para combater o mal.",
    link: "https://en.wikipedia.org/wiki/Dicefolk",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Dicefolk_cover_art.jpg",
    plataforma: "PC",
    genero: "Roguelike",
    dataLancamento: "2024-02-27",
    desenvolvedor: "LEAP Game Studios, Tiny Ghoul",
    notamedia: "Não definido"
  },
  {
    titulo: "Shiren the Wanderer: The Mystery of Serpentcoil Island",
    descricao: "Shiren the Wanderer e seu parceiro furão falante, Koppa, recebem uma visão de uma terra distante e uma garota em perigo, levando-os à misteriosa Ilha Serpentcoil.",
    link: "https://en.wikipedia.org/wiki/Shiren_the_Wanderer:_The_Mystery_of_Serpentcoil_Island",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Shiren_the_Wanderer_Serpentcoil_Island_cover_art.jpg",
    plataforma: "Switch",
    genero: "RPG",
    dataLancamento: "2024-02-27",
    desenvolvedor: "Spike Chunsoft",
    notamedia: "Não definido"
  },
  {
    titulo: "Terror at Oakheart",
    descricao: "Inspirado nos filmes de terror slasher dos anos 80 e 90, Terror at Oakheart leva os jogadores à cidade de Oakheart, aterrorizada pelo assassino conhecido como Teddy.",
    link: "https://en.wikipedia.org/wiki/Terror_at_Oakheart",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Terror_at_Oakheart_cover_art.jpg",
    plataforma: "PC",
    genero: "Terror",
    dataLancamento: "2024-02-27",
    desenvolvedor: "Tainted Pact",
    notamedia: "Não definido"
  },
  {
    titulo: "Wrath: Aeon of Ruin",
    descricao: "Wrath: Aeon of Ruin é um FPS hardcore inspirado nos ícones dos anos 90, alimentado pela lendária tecnologia Quake-1.",
    link: "https://en.wikipedia.org/wiki/Wrath:_Aeon_of_Ruin",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Wrath_Aeon_of_Ruin_cover_art.jpg",
    plataforma: "PC",
    genero: "FPS",
    dataLancamento: "2024-02-27",
    desenvolvedor: "KillPixel Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Brothers: A Tale Of Two Sons Remake",
    descricao: "Guie dois irmãos numa jornada épica de descobertas, perdas, aventuras e mistério reformulada com gráficos, desempenho e jogabilidade de última geração.",
    link: "https://en.wikipedia.org/wiki/Brothers:_A_Tale_of_Two_Sons",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3e/Brothers_A_Tale_of_Two_Sons_cover_art.jpg",
    plataforma: "PS5, Xbox Series X|S, PC",
    genero: "Ação e Aventura",
    dataLancamento: "2024-02-28",
    desenvolvedor: "505 Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Pecaminosa: A Deadly Hand",
    descricao: "Pecaminosa mistura o encanto da pixel art e a mecânica de um RPG de Ação com a atmosfera de film noir.",
    link: "https://en.wikipedia.org/wiki/Pecaminosa:_A_Deadly_Hand",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Pecaminosa_cover_art.jpg",
    plataforma: "PS5, PS4, Xbox Series X|S, Xbox One, Switch, PC",
    genero: "RPG de Ação",
    dataLancamento: "2024-02-28",
    desenvolvedor: "Cereal Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Star Wars: Dark Forces Remaster",
    descricao: "O Império maléfico está atualmente a criar um exército destruidor, a coberto de um véu de mistério. A tua missão é infiltrares-te no Império e acabares com os seus planos de terror e domínio.",
    link: "https://en.wikipedia.org/wiki/Star_Wars:_Dark_Forces",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Star_Wars_Dark_Forces_cover_art.jpg",
    plataforma: "PS5, PS4, Xbox Series X|S, Xbox One, Switch, PC",
    genero: "FPS",
    dataLancamento: "2024-02-28",
    desenvolvedor: "Nightdive Studios",
    notamedia: "78/10"
  },
  {
    titulo: "TimeMelters",
    descricao: "TimeMelters é um jogo de defesa de heróis de estratégia onde você volta no tempo e luta ao lado de suas versões passadas.",
    link: "https://en.wikipedia.org/wiki/TimeMelters",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/TimeMelters_cover_art.jpg",
    plataforma: "PC",
    genero: "Estratégia",
    dataLancamento: "2024-02-28",
    desenvolvedor: "Autoexec Games",
    notamedia: "Não definido"
  },
  {
    titulo: "Anglerfish",
    descricao: "Anglerfish é um jogo de terror de sobrevivência onde cada morte muda o jogo, mantendo a experiência sempre fresca e desafiadora.",
    link: "https://en.wikipedia.org/wiki/Anglerfish_(video_game)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4e/Anglerfish_cover_art.jpg",
    plataforma: ["PS5", "PS4", "Switch"],
    genero: "Terror",
    dataLancamento: "2024-02-29",
    desenvolvedor: "Professional Villains",
    notamedia: "Não definido"
  },
  {
    titulo: "Final Fantasy VII Rebirth",
    descricao: "Final Fantasy VII Rebirth é a segunda parte do remake do clássico RPG Final Fantasy VII, continuando a história de Cloud e seus amigos.",
    link: "https://en.wikipedia.org/wiki/Final_Fantasy_VII_Rebirth",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Final_Fantasy_VII_Rebirth_cover_art.jpg",
    plataforma: ["PS5"],
    genero: "RPG",
    dataLancamento: "2024-02-29",
    desenvolvedor: "Square Enix",
    notamedia: "Não definido"
  },
  {
    titulo: "Welcome to ParadiZe",
    descricao: "Welcome to ParadiZe é um jogo de ação e aventura ambientado em um mundo pós-apocalíptico onde você deve sobreviver e descobrir os segredos de ParadiZe.",
    link: "https://en.wikipedia.org/wiki/Welcome_to_ParadiZe",
    imagem: "https://upload.wikimedia.org/wikipedia/en/6/6e/Welcome_to_ParadiZe_cover_art.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "Ação e Aventura",
    dataLancamento: "2024-02-29",
    desenvolvedor: "ParadiZe Studios",
    notamedia: "Não definido"
  },
  {
    titulo: "Cricket Through the Ages",
    descricao: "Cricket Through the Ages é um jogo de esportes que leva os jogadores através da história do críquete, desde os tempos antigos até o futuro.",
    link: "https://en.wikipedia.org/wiki/Cricket_Through_the_Ages",
    imagem: "https://upload.wikimedia.org/wikipedia/en/7/7e/Cricket_Through_the_Ages_cover_art.jpg",
    plataforma: ["Switch", "PC"],
    genero: "Esportes",
    dataLancamento: "2024-03-01",
    desenvolvedor: "Devolver Digital",
    notamedia: "Não definido"
  },
  {
    titulo: "Sixty Four",
    descricao: "Sixty Four é um jogo de quebra-cabeça onde você deve combinar blocos numerados para alcançar o número 64.",
    link: "https://en.wikipedia.org/wiki/Sixty_Four",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8e/Sixty_Four_cover_art.jpg",
    plataforma: ["PC"],
    genero: "Quebra-cabeça",
    dataLancamento: "2024-03-04",
    desenvolvedor: "Puzzle Games Inc.",
    notamedia: "Não definido"
  },
  {
    titulo: "Final Fantasy VII Rebirth",
    descricao: "Final Fantasy VII Rebirth é o segundo lançamento do projeto de remake de Final Fantasy VII, que reconta em três jogos distintos a história do RPG que redefiniu o gênero.",
    link: "https://pt.wikipedia.org/wiki/Final_Fantasy_VII_Rebirth",
    imagem: "https://upload.wikimedia.org/wikipedia/en/8/8d/Final_Fantasy_VII_Rebirth_cover_art.jpg",
    plataforma: ["PS5"],
    genero: "RPG",
    dataLancamento: "2024-02-29",
    desenvolvedor: "Square Enix",
    notamedia: "Não definido"
  },
  {
    titulo: "Welcome to ParadiZe",
    descricao: "Em Welcome to ParadiZe, o paraíso não é bem como se imagina: ele está infestado de zumbis! Felizmente, você pode controlá-los.",
    link: "https://pt.wikipedia.org/wiki/Welcome_to_ParadiZe",
    imagem: "https://upload.wikimedia.org/wikipedia/en/4/4d/Welcome_to_ParadiZe_cover_art.jpg",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "Ação e Aventura",
    dataLancamento: "2024-02-29",
    desenvolvedor: "Eko Software",
    notamedia: "Não definido"
  },
  {
    titulo: "Cricket Through the Ages",
    descricao: "Cricket Through the Ages é um jogo de física e ação que explora a história do críquete de uma maneira divertida e única.",
    link: "https://pt.wikipedia.org/wiki/Cricket_Through_the_Ages",
    imagem: "https://upload.wikimedia.org/wikipedia/en/3/3d/Cricket_Through_the_Ages_cover_art.jpg",
    plataforma: ["Switch", "PC"],
    genero: "Ação",
    dataLancamento: "2024-03-01",
    desenvolvedor: "Free Lives",
    notamedia: "Não definido"
  },
  {
    titulo: "Sixty Four",
    descricao: "Sixty Four é um jogo de simulação minimalista onde você transforma máquinas simples em uma fábrica próspera.",
    link: "https://pt.wikipedia.org/wiki/Sixty_Four",
    imagem: "https://upload.wikimedia.org/wikipedia/en/2/2d/Sixty_Four_cover_art.jpg",
    plataforma: ["PC"],
    genero: "Simulação",
    dataLancamento: "2024-03-04",
    desenvolvedor: "Oleg Danilov",
    notamedia: "Não definido"
  },
  {
    titulo: "The Thaumaturge",
    descricao: "The Thaumaturge é um RPG baseado em história com escolhas moralmente ambíguas, ambientado na Varsóvia do início do século XX.",
    link: "https://pt.wikipedia.org/wiki/The_Thaumaturge",
    imagem: "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Thaumaturge_cover_art.jpg",
    plataforma: ["PC"],
    genero: "RPG",
    dataLancamento: "2024-03-04",
    desenvolvedor: "Fool's Theory",
    notamedia: "Não definido"
  },
  {
    titulo: "Classified: France '44",
    descricao: "Jogo de estratégia por turnos ambientado na Segunda Guerra Mundial.",
    link: "https://pt.wikipedia.org/wiki/Classified:_France_'44",
    plataforma: ["PS5", "Xbox Series X|S", "PC"],
    genero: "Estratégia",
    dataLancamento: "2024-03-05",
    desenvolvedor: "Absolutely Games",
    notamedia: "Não definido"
  },
  {
    titulo: "FloraMancer",
    descricao: "Jogo de ação e agricultura onde você cultiva plantas mágicas para criar feitiços.",
    link: "https://pt.wikipedia.org/wiki/FloraMancer",
    plataforma: ["PC"],
    genero: "Ação, Agricultura",
    dataLancamento: "2024-03-05",
    desenvolvedor: "Brookwood Games",
    notamedia: "Não definido"
  },
  {
    titulo: "The Outlast Trials",
    descricao: "Jogo de terror cooperativo onde você é um cobaia em experimentos de controle mental.",
    link: "https://pt.wikipedia.org/wiki/The_Outlast_Trials",
    plataforma: ["PS5", "PS4", "Xbox Series X|S", "Xbox One", "PC"],
    genero: "Terror, Cooperativo",
    dataLancamento: "2024-03-05",
    desenvolvedor: "Red Barrels",
    notamedia: "7.4/10"
  },
  {
    titulo: "Quilts and Cats of Calico",
    descricao: "Jogo de tabuleiro onde você costura colchas e atrai gatos adoráveis.",
    link: "https://pt.wikipedia.org/wiki/Quilts_and_Cats_of_Calico",
    plataforma: ["Switch", "PC"],
    genero: "Puzzle, Tabuleiro",
    dataLancamento: "2024-03-05",
    desenvolvedor: "Monster Couch",
    notamedia: "Não definido"
  },
  {
    titulo: "Hex Gambit: Respawned",
    descricao: "Jogo de tabuleiro digital competitivo com estratégia por turnos.",
    link: "https://pt.wikipedia.org/wiki/Hex_Gambit:_Respawned",
    plataforma: ["PC", "PS5", "PS4", "Xbox Series X|S", "Xbox One", "Switch"],
    genero: "Estratégia, Tabuleiro",
    dataLancamento: "2024-03-06",
    desenvolvedor: "One Man Left Studios",
    notamedia: "Não definido"
  },
  {
    titulo: "Concord",
    descricao: "Concord é um hero shooter de ficção científica jogado em uma perspectiva de primeira pessoa. O jogo apresenta uma variedade de personagens alienígenas, cada um com habilidades diferentes.",
    link: "https://pt.wikipedia.org/wiki/Concord_(jogo_eletr%C3%B4nico)",
    imagem: "https://upload.wikimedia.org/wikipedia/en/5/5e/Concord_video_game_cover.jpg",
    plataforma: ["PlayStation 5", "Windows"],
    genero: "Hero shooter",
    dataLancamento: "23 de agosto de 2024",
    desenvolvedor: "Firewalk Studios",
    notamedia: "65/100"
  },
  ]